"""Deterministic auth-contract test file rendering.

After AuthAgent finishes (post-loop reconcile + audit), it emits a
test file per backend service that asserts the runtime auth contract
holds against the live stack:
  - JWKS endpoint reachable + has at least one RS-family key
  - Each test user named in AUTH_CONTRACT.md can log in
  - Each user's JWT decodes with expected ``iss`` and ``roles``

The test file is regenerated each AuthAgent run from the contract
markdown. It lives in the workspace and runs during the integration
phase via the pytest sidecar — same execution surface as Coder-
written integration tests.

Why deterministic (no LLM): the contract is structured enough that
templating is reliable, and the LLM would just hallucinate details
the audit already knows for sure (test user emails, role names,
issuer URL).

This module is pure render — caller is responsible for writing the
result to disk at the right path.
"""
from __future__ import annotations

from typing import List, Tuple

from bizniz.auth_agent.audits import _parse_issuer, _parse_test_users


_FILE_HEADER = '''"""Auth contract tests — auto-generated by AuthAgent.

DO NOT EDIT: this file is regenerated each AuthAgent run from
AUTH_CONTRACT.md. Manual edits will be overwritten.

Asserts the runtime auth contract holds against the live FusionAuth
stack: JWKS reachable, every contract test user can log in, and each
JWT decodes with the expected issuer + roles.

Runs in the integration phase (pytest sidecar joined to the compose
network — ``http://auth:9011`` resolves).
"""
import os
import json
import base64
from typing import Tuple

import httpx
import pytest


# FUSIONAUTH_URL is the in-network URL every container carries (points
# at the architecture's actual FA service name). FUSIONAUTH_HOST_URL is
# host-perspective and lives in .env.host — absent inside containers
# since the 2026-08-04 env split; kept for host-side runs. The
# hardcoded fallback assumes a service named "auth", which is only a
# guess (muvnit named it "fusionauth" — the v16-era fallback broke
# there).
_FA_URL = (
    os.environ.get("FUSIONAUTH_URL")
    or os.environ.get("FUSIONAUTH_HOST_URL")
    or "http://auth:9011"
)
_APP_ID = "__APP_ID_PLACEHOLDER__"
_ISSUER = "__ISSUER_PLACEHOLDER__"


def _decode_jwt_payload(token: str) -> dict:
    """Decode a JWT's payload without verifying the signature.

    Used here only to inspect claims; the SERVER-side code does
    proper RS256 verification via the JWKS document.
    """
    parts = token.split(".")
    if len(parts) != 3:
        raise ValueError(f"malformed JWT: {len(parts)} parts")
    payload_b64 = parts[1]
    # base64 with stripped padding — pad to multiple of 4.
    padded = payload_b64 + "=" * (-len(payload_b64) % 4)
    return json.loads(base64.urlsafe_b64decode(padded))


def _login(email: str, password: str) -> Tuple[int, dict]:
    r = httpx.post(
        f"{_FA_URL}/api/login",
        json={
            "applicationId": _APP_ID,
            "loginId": email,
            "password": password,
        },
        timeout=15,
    )
    try:
        body = r.json()
    except Exception:
        body = {"raw": r.text}
    return r.status_code, body
'''


_JWKS_TEST = '''
def test_jwks_reachable_and_rs_signed():
    """JWKS endpoint must be reachable and contain at least one RS-
    family key. Without this, the backend's ``algorithms=['RS256']``
    JWT verification has no key to verify with."""
    r = httpx.get(f"{_FA_URL}/.well-known/jwks.json", timeout=10)
    assert r.status_code == 200, (
        f"JWKS endpoint returned {r.status_code}: {r.text[:200]}"
    )
    keys = r.json().get("keys", [])
    assert keys, "JWKS document has zero keys"
    rs_keys = [k for k in keys if (k.get("alg") or "").upper().startswith("RS")]
    assert rs_keys, (
        f"JWKS has {len(keys)} key(s) but none are RS-family: "
        f"{[k.get('alg') for k in keys]}"
    )
'''


_USER_TEST_TEMPLATE = '''

def test_user_login___SLUG__():
    """Test user `__EMAIL__` (roles: __ROLES_LIST__) must log in
    cleanly and receive an RS256 JWT. Audit was green at AuthAgent
    submit time; this is the runtime regression guard."""
    status, body = _login("__EMAIL__", "__PASSWORD__")
    assert status == 200, (
        f"login for __EMAIL__ returned {status}: {body}"
    )
    token = body.get("token")
    assert token, f"login for __EMAIL__ returned no token: {body}"
    payload = _decode_jwt_payload(token)
    __ISSUER_ASSERTION__
    roles = payload.get("roles") or []
    expected = __EXPECTED_ROLES_REPR__
    for role in expected:
        assert role in roles, (
            f"user __EMAIL__ JWT missing expected role {role!r}; got {roles}"
        )
'''


def render_auth_contract_test_file(
    *,
    contract_markdown: str,
    primary_app_id: str,
) -> str:
    """Render the full auth contract test file as a single Python source.

    Returns the file content. Caller writes it to the appropriate
    workspace path. Empty contract / no test users still produces a
    file (with just the JWKS test) — better to have a regression
    floor than to silently emit nothing.
    """
    issuer = _parse_issuer(contract_markdown) or ""
    users = _parse_test_users(contract_markdown)

    head = (
        _FILE_HEADER
        .replace("__APP_ID_PLACEHOLDER__", primary_app_id)
        .replace("__ISSUER_PLACEHOLDER__", issuer)
    )

    parts: List[str] = [head, _JWKS_TEST]

    for email, password, roles in users:
        parts.append(_render_user_test(email, password, list(roles), issuer))

    return "".join(parts).rstrip() + "\n"


def _render_user_test(
    email: str, password: str, roles: List[str], issuer: str,
) -> str:
    """One test_user_login_<slug> function per contract user."""
    slug = _slugify(email)
    if issuer:
        issuer_assertion = (
            'iss = payload.get("iss") or ""\n'
            '    assert iss == _ISSUER, (\n'
            '        f"user iss claim mismatch: expected {_ISSUER!r}, got {iss!r}"\n'
            '    )'
        )
    else:
        issuer_assertion = "# (no issuer in contract; skipping iss assertion)"
    return (
        _USER_TEST_TEMPLATE
        .replace("__SLUG__", slug)
        .replace("__EMAIL__", email)
        .replace("__PASSWORD__", password)
        .replace("__ROLES_LIST__", ", ".join(roles) or "(none)")
        .replace("__EXPECTED_ROLES_REPR__", repr(roles))
        .replace("__ISSUER_ASSERTION__", issuer_assertion)
    )


def _slugify(email: str) -> str:
    """Make a python-identifier-safe slug from an email."""
    out_chars = []
    for ch in email.lower():
        if ch.isalnum():
            out_chars.append(ch)
        else:
            out_chars.append("_")
    slug = "".join(out_chars).strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug or "user"
