"""AUTH_CONTRACT.md renderer.

Pure render: AuthManifest → markdown, dispatching on the manifest's
provider. The manifest reflects what the identity provider actually
has, so the contract can NEVER claim a user or role that doesn't exist — that whole class of v1/v2 bug
(``AuthAgent: audit FAIL [test_users_in_fa]``) goes away by
construction.
"""
from __future__ import annotations

from bizniz.auth_operator.manifest import AuthManifest


def render_auth_contract(manifest: AuthManifest) -> str:
    """Render AUTH_CONTRACT.md from the post-apply manifest.

    Dispatches on the provider: the two APIs share nothing beyond issuing a JWT, so a
    FusionAuth contract handed to code talking to Keycloak is worse than no contract.
    """
    if manifest.provider == "keycloak":
        from bizniz.auth_operator.keycloak_contract import render_keycloak_contract

        return render_keycloak_contract(manifest)

    lines: list[str] = []
    lines.append("# Auth Contract")
    lines.append("")
    lines.append(
        "**Auto-generated by FusionAuthOperator. DO NOT EDIT** — "
        "regenerated each AuthAgent run from live FusionAuth state. "
        "Manual edits will be overwritten."
    )
    lines.append("")

    lines.append("## FusionAuth coordinates")
    lines.append("")
    lines.append(f"- Host URL: `{manifest.fa_url}`")
    lines.append(f"- Primary application ID: `{manifest.primary_app_id}`")
    lines.append(f"- Tenant ID: `{manifest.tenant_id}`")
    if manifest.issuer:
        lines.append(f"- Issuer (iss claim): `{manifest.issuer}`")
    lines.append("")

    lines.append("## JWT signing")
    lines.append("")
    sk = manifest.signing_key
    bound = []
    if sk.bound_to_app:
        bound.append("application")
    if sk.bound_to_tenant:
        bound.append("tenant")
    bound_str = " + ".join(bound) if bound else "(unbound)"
    lines.append(
        f"- Algorithm: **{sk.algorithm}** "
        f"({'RS-family ✓' if sk.is_rs_family else 'NOT RS-family ✗'})"
    )
    lines.append(f"- Key ID: `{sk.key_id or '(none)'}`")
    lines.append(f"- Bound to: {bound_str}")
    lines.append("")

    if manifest.applications:
        lines.append("## Applications")
        lines.append("")
        for app in manifest.applications:
            lines.append(
                f"- **{app.name}** (`{app.application_id}`) — "
                f"roles: {', '.join(app.role_names) or '(none)'}"
            )
        lines.append("")

    if manifest.roles:
        lines.append("## Roles")
        lines.append("")
        for role in manifest.roles:
            sup = " *[super_role]*" if role.is_super_role else ""
            desc = f" — {role.description}" if role.description else ""
            lines.append(f"- `{role.name}`{sup}{desc}")
        lines.append("")

    if manifest.users:
        lines.append("## Test users")
        lines.append("")
        lines.append(
            "Format: `email / password — roles role_name[, role_name]`. "
            "Used by integration tests; passwords are dev convention "
            "(production rotates on first login)."
        )
        lines.append("")
        for user in manifest.users:
            roles_str = ", ".join(user.roles) or "(none)"
            verified = " ✓" if user.login_verified else " ✗ login unverified"
            lines.append(
                f"- {user.email} / {user.password} — roles {roles_str}"
                f"{verified}"
            )
        lines.append("")

    # ── Deterministic FusionAuth API reference ──────────────────────────
    # The code-samples section (LLM-generated, optional) covers idiomatic
    # snippets. This block is the canonical fact sheet so engineers
    # can't get the URL shape wrong even if samples are missing or
    # ambiguous. Source of every "registered for application [X] / user
    # [X] already exists" 400 is putting the app ID where the user ID
    # goes — call this out unambiguously here.
    lines.append("## FusionAuth API — endpoint reference")
    lines.append("")
    lines.append(
        "Auth header for ALL admin calls below: "
        "`Authorization: <FUSIONAUTH_API_KEY>` (raw API key, NOT "
        "`Bearer ...`). Read the key from the `FUSIONAUTH_API_KEY` "
        "env var. The API key is provisioned by the auth orchestrator "
        "and injected into every service container."
    )
    lines.append("")
    lines.append("### Login (issue a JWT for an existing user)")
    lines.append("")
    lines.append("- Method: `POST`")
    lines.append("- URL: `http://auth:9011/api/login` (no path arg)")
    lines.append("- No `Authorization` header required.")
    lines.append(
        "- Body: `{\"loginId\": \"<email>\", \"password\": \"...\", "
        "\"applicationId\": \"" + str(manifest.primary_app_id) + "\"}`"
    )
    lines.append("- Returns: `{\"token\": \"<JWT>\", \"user\": {...}}`")
    lines.append("")
    lines.append("### Register a NEW user (combined create-user + register)")
    lines.append("")
    lines.append("- Method: `POST`")
    lines.append(
        "- URL: `http://auth:9011/api/user/registration` "
        "(**no path argument**)"
    )
    lines.append("- Header: `Authorization: <FUSIONAUTH_API_KEY>`")
    lines.append(
        "- Body: `{\"user\": {\"email\": \"...\", \"password\": \"...\", "
        "\"fullName\": \"...\"}, \"registration\": {\"applicationId\": "
        "\"" + str(manifest.primary_app_id) + "\", \"roles\": "
        "[\"<role>\"]}}`"
    )
    lines.append("- Returns: `{\"user\": {\"id\": \"<uuid>\", ...}, \"registration\": {...}}`")
    lines.append("")
    lines.append(
        "**Pitfall — do NOT use the path-arg form for new users.** "
        "`POST /api/user/registration/{userId}` registers an "
        "**existing** user for an application; it requires the user "
        "to already exist. Passing the app ID in that path slot "
        "(common mistake — they're both UUIDs) returns 400 with "
        "`{\"fieldErrors\":{\"registration\":[{\"code\":"
        "\"[duplicate]registration\"...}]}}` and `userId` "
        "echoed as the same UUID you sent. If you see that error, "
        "switch to the no-path-arg URL above."
    )
    lines.append("")
    lines.append("### Change a user's roles")
    lines.append("")
    lines.append("- Method: `PATCH`")
    lines.append(
        "- URL: `http://auth:9011/api/user/registration/{userId}` "
        "(this IS the path-arg endpoint — for updates, not creation)"
    )
    lines.append("- Header: `Authorization: <FUSIONAUTH_API_KEY>`")
    lines.append(
        "- Body: `{\"registration\": {\"applicationId\": "
        "\"" + str(manifest.primary_app_id) + "\", \"roles\": "
        "[\"<role>\", ...]}}`"
    )
    lines.append("")
    lines.append("### Password policy (default tenant settings)")
    lines.append("")
    lines.append(
        "- Minimum length: 8 characters"
    )
    lines.append(
        "- Required character classes: mixed case, digit, symbol"
    )
    lines.append(
        "- Weak-password rejection: 400 with "
        "`fieldErrors.user.password = [...]`"
    )
    lines.append(
        "- Test-friendly password that passes: `Password123!`"
    )
    lines.append("")
    lines.append("### Validate a JWT")
    lines.append("")
    lines.append(
        "- Fetch JWKS from `http://auth:9011/.well-known/jwks.json` "
        "(no auth header)."
    )
    lines.append(
        f"- Decode with algorithms=`[\"{sk.algorithm}\"]`, "
        f"audience=`{manifest.primary_app_id}`, "
        f"issuer=`{manifest.issuer or '(see iss claim)'}`."
    )
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"
