"""AUTH_CONTRACT.md for a Keycloak realm.

Pure render: AuthManifest → markdown. The manifest is read from the live realm, so the
contract can never claim a role or a user that does not exist.

The endpoint reference is the point of this file. Keycloak has two APIs that answer on
similar-looking URLs with completely different authentication, and generated code that
confuses them fails in ways that read like a permissions problem:

* the **token endpoint** on the realm, which takes a user's own credentials;
* the **admin API**, which takes this service's service-account bearer.
"""
from __future__ import annotations

from bizniz.auth_operator.manifest import AuthManifest


def render_keycloak_contract(manifest: AuthManifest) -> str:
    lines: list[str] = []
    add = lines.append

    realm_url = manifest.fa_url.rstrip("/")
    realm = manifest.tenant_id
    client = manifest.primary_app_id

    add("# Auth Contract")
    add("")
    add("**Auto-generated by KeycloakOperator. DO NOT EDIT** — regenerated from the live "
        "realm on each run. Manual edits will be overwritten.")
    add("")

    add("## Keycloak coordinates")
    add("")
    add(f"- Realm URL: `{realm_url}`")
    add(f"- Realm: `{realm}`")
    add(f"- Client ID: `{client}`")
    add(f"- Token endpoint: `{realm_url}/protocol/openid-connect/token`")
    add(f"- JWKS: `{realm_url}/protocol/openid-connect/certs`")
    if manifest.issuer:
        add(f"- Issuer (`iss` claim): `{manifest.issuer}`")
    add("")

    add("## Verifying a token")
    add("")
    add(f"Tokens are signed `{manifest.signing_key.algorithm}` "
        f"(key id `{manifest.signing_key.key_id or 'unknown'}`) and verified **locally** "
        "against the JWKS above. Do not call Keycloak to validate a bearer: that is a "
        "round trip per request and an outage whenever Keycloak hiccups.")
    add("")
    add("Three things reject a valid token if you get them wrong:")
    add("")
    add("1. **The issuer follows the hostname the token was fetched through.** A token "
        "obtained through the published port says `http://localhost:<port>/realms/"
        f"{realm}`; one obtained inside the docker network says `{realm_url}`. Accept "
        "every value in `KEYCLOAK_ISSUERS`, not one.")
    add("2. **The audience is `account`** unless the realm has an audience mapper. This "
        f"realm has one for `{client}`, so check `aud` against `KEYCLOAK_AUDIENCES`.")
    add("3. **Realm roles live in `realm_access.roles`.** This realm also maps them to a "
        "flat `roles` claim. Read both, plus `resource_access.<client>.roles`.")
    add("")

    if manifest.roles:
        add("## Roles")
        add("")
        for role in manifest.roles:
            suffix = f" — {role.description}" if role.description else ""
            add(f"- `{role.name}`{suffix}")
        add("")

    if manifest.users:
        add("## Seeded users")
        add("")
        add("Each was logged in after creation, so `login verified` is a fact rather than "
            "an assumption.")
        add("")
        add("| Email | Roles | Login verified |")
        add("|---|---|---|")
        for user in manifest.users:
            roles = ", ".join(f"`{r}`" for r in user.roles) or "—"
            add(f"| `{user.email}` | {roles} | {'yes' if user.login_verified else '**no**'} |")
        add("")

    add("## Keycloak API — endpoint reference")
    add("")
    add("Two APIs, two kinds of credential. Mixing them is the source of most 401s and "
        "403s in generated code.")
    add("")

    add("### Log a user in (the direct access grant)")
    add("")
    add("- Method: `POST`")
    add(f"- URL: `{realm_url}/protocol/openid-connect/token`")
    add("- Content type: **form-encoded**, not JSON.")
    add(f"- Body: `grant_type=password&client_id={client}"
        "&client_secret=$KEYCLOAK_CLIENT_SECRET&username=<email>&password=...&scope=openid`")
    add("- Returns: `{\"access_token\": \"<JWT>\", \"refresh_token\": \"...\"}`")
    add("")

    add("### Refresh")
    add("")
    add("- Same URL, `grant_type=refresh_token&refresh_token=...` plus the client id and "
        "secret.")
    add("")

    add("### Act as this service (for every admin call below)")
    add("")
    add("- Method: `POST`")
    add(f"- URL: `{realm_url}/protocol/openid-connect/token`")
    add(f"- Body: `grant_type=client_credentials&client_id={client}"
        "&client_secret=$KEYCLOAK_CLIENT_SECRET`")
    add("- Use the returned token as `Authorization: Bearer <token>` — the admin API "
        "takes a bearer, unlike FusionAuth's raw API key.")
    add("")

    add("### Create a user")
    add("")
    add("- Method: `POST`")
    add(f"- URL: `{realm_url.rsplit('/realms/', 1)[0]}/admin/realms/{realm}/users`")
    add("- Header: `Authorization: Bearer <service-account token>`")
    add("- Body: `{\"username\": \"<email>\", \"email\": \"<email>\", \"enabled\": true, "
        "\"credentials\": [{\"type\": \"password\", \"value\": \"...\", "
        "\"temporary\": false}]}`")
    add("- Returns **201 with an empty body**. The new user's id is in the `Location` "
        "header, or fetch it with `GET /users?email=<email>&exact=true`.")
    add("")

    add("### Assign realm roles")
    add("")
    add("- Method: `POST`")
    add(f"- URL: `.../admin/realms/{realm}/users/{{userId}}/role-mappings/realm`")
    add("- Body: the **full role representations** from `GET /admin/realms/"
        f"{realm}/roles`, not just their names. Posting `[{{\"name\": \"admin\"}}]` "
        "silently assigns nothing.")
    add("")

    add("### Password reset and email verification")
    add("")
    add("- Method: `PUT`")
    add(f"- URL: `.../admin/realms/{realm}/users/{{userId}}/execute-actions-email`")
    add("- Body: `[\"UPDATE_PASSWORD\"]` or `[\"VERIFY_EMAIL\"]`")
    add("- Keycloak emails the user a link and handles the change itself. **Never accept "
        "a new password in application code** — there is no endpoint for it here, and "
        "adding one puts credential handling back where it does not belong.")
    add("")

    add("### Pitfalls")
    add("")
    add("- The admin API needs the service account to hold the realm-management role "
        "`manage-users`. Without it every call above returns 403, which reads like a bad "
        "token and is not.")
    add("- The token endpoint takes form encoding. Sending JSON returns "
        "`400 unsupported_grant_type`, which does not mention the content type.")
    add("- `POST /users` answers 409 when the email exists. Treat it as \"already there\" "
        "and look the user up rather than failing the request.")
    add("")

    return "\n".join(lines)
